<a href="https://colab.research.google.com/github/anujv4312-stack/100_days_of_ML/blob/main/ordinal%26label_encode_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd



1.   on gender we will use one hot encoding
2.   review and education we will use ordinal
3.   on purchased mean output(Y) we will use label encoding

In [2]:
df = pd.read_csv('/content/customer.csv')
df.sample(5)

    age  gender   review education purchased
13   57  Female  Average    School        No
39   76    Male     Poor        PG        No
14   15    Male     Poor        PG       Yes
33   89  Female     Good        PG       Yes
19   97    Male     Poor        PG       Yes

In [3]:
df = df.iloc[:,2:]
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,:2],df.iloc[:,-1],test_size = 0.2)

In [21]:
x_train

     review education
4   Average        UG
5   Average    School
30  Average        UG
29  Average        UG
39     Poor        PG
0   Average    School
13  Average    School
10     Good        UG
44  Average        UG
7      Poor    School
46     Poor        PG
33     Good        PG
3      Good        PG
49     Good        UG
45     Poor        PG
17     Poor        UG
41     Good        PG
20  Average    School
34  Average    School
47     Good        PG
18     Good    School
22     Poor        PG
48     Good        UG
43     Poor        PG
14     Poor        PG
8   Average        UG
19     Poor        PG
11     Good        UG
35     Poor    School
6      Good    School
2      Good        PG
28     Poor    School
15     Poor        UG
37  Average        PG
38     Good    School
36     Good        UG
25     Good    School
32  Average        UG
42     Good        PG
40     Good    School

In [24]:
y_train

4      No
5     Yes
30     No
29    Yes
39     No
0      No
13     No
10    Yes
44     No
7     Yes
46     No
33    Yes
3      No
49     No
45    Yes
17    Yes
41    Yes
20    Yes
34     No
47    Yes
18     No
22    Yes
48    Yes
43     No
14    Yes
8      No
19    Yes
11    Yes
35    Yes
6      No
2      No
28     No
15     No
37    Yes
38     No
36    Yes
25     No
32    Yes
42    Yes
40     No
Name: purchased, dtype: object

**ORDINAL ENCODING**

In [22]:
from sklearn.preprocessing import OrdinalEncoder



oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']]);

# Fit the encoder on the original string data
oe.fit(x_train)

# Transform both training and testing sets
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [23]:
x_train

array([[1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [1., 2.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [2., 0.]])

**LABEL ENCODING**

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [26]:
y_train

array([0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0])