In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv(r'C:\Users\LENOVO\Desktop\machine learning\100_days_of_ML\day_33_wrking_with_date&time\orders.csv')
time = pd.read_csv(r'C:\Users\LENOVO\Desktop\machine learning\100_days_of_ML\day_33_wrking_with_date&time\messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [3]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

WORKING WITH DATES

In [7]:
#Convert the date column to datetime format
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

1) EXTRACTING YEAR

In [9]:
date['date_year'] = date['date'].dt.year

In [10]:
date.sample(5)

          date  product_id  city_id  orders  date_year
204 2018-10-07         820       30       2       2018
708 2019-06-05        5004       25       5       2019
686 2018-12-29        1715       16       1       2018
361 2018-10-13         124       26       2       2018
158 2019-12-16        2148       28      51       2019

2) EXCTRACTING MONTHS

In [11]:
date['date_month'] = date['date'].dt.month

In [12]:
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [14]:
date['date_month_name'] = date['date'].dt.month_name()

In [15]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

EXTRACTING DAYS

In [16]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [17]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [18]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

CHECK IF THE DAY IS WEEKEND

In [19]:
date['isWeekend'] = np.where(date['date_dow_name'].isin(['Saturday','Sunday']),1,0)

In [20]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,isWeekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

#extract week of the year

In [23]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,isWeekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

EXTRACT QUARTER

In [24]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,isWeekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

EXTRACT SEMESTER

In [25]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,isWeekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

EXTRACT TIME ELAPSED DATA

In [26]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 9, 1, 23, 12, 46, 732406)

In [27]:
today - date['date']

0     2457 days 23:12:46.732406
1     2939 days 23:12:46.732406
2     2870 days 23:12:46.732406
3     2572 days 23:12:46.732406
4     2795 days 23:12:46.732406
                 ...
995   2885 days 23:12:46.732406
996   2826 days 23:12:46.732406
997   2674 days 23:12:46.732406
998   2739 days 23:12:46.732406
999   2513 days 23:12:46.732406
Name: date, Length: 1000, dtype: timedelta64[us]

In [28]:
(today - date['date']).dt.days

0      2457
1      2939
2      2870
3      2572
4      2795
       ...
995    2885
996    2826
997    2674
998    2739
999    2513
Name: date, Length: 1000, dtype: int64

In [30]:
# Months passed

date['months_passed'] = (
    (today.year - date['date'].dt.year) * 12
    + (today.month - date['date'].dt.month)
)

In [31]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,isWeekend,date_week,quarter,semester,months_passed
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2,81
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2,97
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2,95
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2,85
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1,92

WORKING WITH TIME

In [32]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [33]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [34]:
time['date'] = pd.to_datetime(time['date'])

In [35]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

In [36]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

EXTRACT TIME PART

In [37]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [38]:
today - time['date']

0     4643 days 22:22:46.732406
1     4507 days 23:32:46.732406
2     4993 days 22:51:46.732406
3     4295 days 22:41:46.732406
4     4693 days 00:01:46.732406
                 ...
995   5282 days 22:22:46.732406
996   4603 days 23:58:46.732406
997   5068 days 23:35:46.732406
998   5184 days 23:38:46.732406
999   4456 days 23:47:46.732406
Name: date, Length: 1000, dtype: timedelta64[us]

In [39]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      4.012358e+08
1      3.894896e+08
2      4.314775e+08
3      3.711697e+08
4      4.054753e+08
           ...
995    4.564454e+08
996    3.977855e+08
997    4.379601e+08
998    4.479827e+08
999    3.850841e+08
Name: date, Length: 1000, dtype: float64

In [40]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.687263e+06
1      6.491493e+06
2      7.191292e+06
3      6.186162e+06
4      6.757922e+06
           ...
995    7.607423e+06
996    6.629759e+06
997    7.299336e+06
998    7.466379e+06
999    6.418068e+06
Name: date, Length: 1000, dtype: float64

In [41]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      111454.379648
1      108191.546315
2      119854.862981
3      103102.696315
4      112632.029648
           ...
995    126790.379648
996    110495.979648
997    121655.596315
998    124439.646315
999    106967.796315
Name: date, Length: 1000, dtype: float64